name: School of Man
favicon: null
layout_spectrum: 0.606383
typography_spectrum: 0.112766
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FCFCFE'
    - '#D4CCC1'
    - '#100D14'
    - '#778496'
    - '#99ADC6'
  brandStrength: 0.6875
  lightness: 0.5765957
  saturation: 0.625
  rhythmicContrast: 0.6085106
purpose: []
