favicon: null
name: School of Man
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.008521283511072397
  brandStrength: 0.1110958780627698
  lightness: 0.8721094601787627
  brandColors:
    - '#FFFFFF'
    - '#2C2827'
    - '#554C45'
    - '#7C8787'
    - '#C2CFC0'
  rhythmicContrast: 0.7546429724898189
typography_spectrum: 0.09787234
layout_spectrum: 0.01702128
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
